<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Special Request Code_special_request_code</name>
   <tag></tag>
   <elementGuidId>b45c20b2-9502-4b34-81b6-53cc60d90d4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = 'special_request_code' and @id = 'special_request_code' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#special_request_code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f302afe-0b07-44dc-a0ab-4693d9f4b003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b935e1f4-af4c-4082-8cdc-1f2d3b458fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Special Request Code</value>
      <webElementGuid>b7960476-0b63-45b0-865c-1fdbee852b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>special_request_code</value>
      <webElementGuid>f2773910-95b1-4676-ae62-3d05035172e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>special_request_code</value>
      <webElementGuid>c5b15da6-2ffa-4f2b-9fd6-a759e34726f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cl</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>5f708903-b973-4c4a-9ee9-45c894a0f6c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cr</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>36503486-a2e0-4fda-a262-2dee78b903f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>708d3f9f-8755-4396-8304-8cc3738d3f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>39355844-d3e7-4b81-a711-74a3a1b5cded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>36</value>
      <webElementGuid>ea0a7e61-c631-4e73-b867-34de4401602c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hint</name>
      <type>Main</type>
      <value>The code of the special request.</value>
      <webElementGuid>ccc57bba-9020-4ed9-bdb3-3676dcc59fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;special_request_code&quot;)</value>
      <webElementGuid>a2066d60-c4bd-45aa-93fe-fe433acb244e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='special_request_code']</value>
      <webElementGuid>5cf769f4-a24b-4f3c-b555-a0fe35ad83a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section/form/div/div/div/div[3]/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>c5af6928-76c8-4532-92c8-436d373890d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>016225fc-49e8-4b37-a43d-aacde6feb7f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'special_request_code' and @id = 'special_request_code' and @type = 'text']</value>
      <webElementGuid>09f9a6f4-1807-4fca-9259-d10128fe12f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
