<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Basic Information_MuiAvatar-root MuiAvatar-circular jss97 css-1jpfvo9</name>
   <tag></tag>
   <elementGuidId>3ebb4fab-ce1f-483d-8001-b5439303168a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiAvatar-root.MuiAvatar-circular.jss97.css-1jpfvo9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>24ad4d05-b3b8-4afd-ba5b-fe1a231efb4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAvatar-root MuiAvatar-circular jss97 css-1jpfvo9</value>
      <webElementGuid>6c7ff56c-4f3c-40bc-b60f-be3108a6072a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;jss59&quot;]/div[@class=&quot;jss71&quot;]/div[@class=&quot;jss72&quot;]/div[@class=&quot;jss77&quot;]/div[@class=&quot;jss79&quot;]/div[@class=&quot;jss95 MuiBox-root css-0&quot;]/div[@class=&quot;jss96 MuiBox-root css-0&quot;]/div[@class=&quot;MuiAvatar-root MuiAvatar-circular jss97 css-1jpfvo9&quot;]</value>
      <webElementGuid>4adfc26d-689d-4f0c-a138-b4f080fc68b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/div/div/div/div</value>
      <webElementGuid>9fd23def-7666-4056-84e4-820e09b7bce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic Information'])[1]/preceding::div[1]</value>
      <webElementGuid>71f3599a-cca5-44be-bb29-8d1ab6ac190e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::div[3]</value>
      <webElementGuid>eb55ba5b-4060-4f0c-9938-093af9689394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div</value>
      <webElementGuid>b70d403c-300a-440c-b699-c61987f067b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
