<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_My Organization_01_rounded-circle</name>
   <tag></tag>
   <elementGuidId>806491ab-96c1-4f68-a13e-d218c413b870</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.rounded-circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top-right-navbar']/button[3]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2248d448-1384-446c-b56e-b41e5eb8e6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>83b74aca-6c02-4094-9a63-995faae9438c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>02eeb808-e53b-469e-a64a-7fc5c5978294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-circle</value>
      <webElementGuid>6e9f818a-57f3-4340-8a2a-f55ba4ebd94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://katalon-test.s3.amazonaws.com/ab19f636-2a34-4b2c-8f62-089881524311</value>
      <webElementGuid>e8ce653b-d607-4ac3-8b9a-b3356e8a5950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>crNnzzEfNT</value>
      <webElementGuid>174c3631-88ff-42cd-80f2-8231073b3789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>crNnzzEfNT</value>
      <webElementGuid>71b8dcd7-b265-41a3-8b7a-5b389fcfc64d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-right-navbar&quot;)/button[@class=&quot;MuiButtonBase-root MuiIconButton-root MuiIconButton-sizeLarge css-resnt5&quot;]/div[@class=&quot;avatar&quot;]/img[@class=&quot;rounded-circle&quot;]</value>
      <webElementGuid>ed0b702d-4724-49f3-bf9b-711c0f039f41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top-right-navbar']/button[3]/div/img</value>
      <webElementGuid>c8f2e25a-d201-438a-95da-42235ad86cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='crNnzzEfNT']</value>
      <webElementGuid>3c9068cc-fb85-4321-9478-f37c36a8ce9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>02af2dd8-fee4-4d98-b4c6-79fbc213912b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://katalon-test.s3.amazonaws.com/ab19f636-2a34-4b2c-8f62-089881524311' and @title = 'crNnzzEfNT' and @alt = 'crNnzzEfNT']</value>
      <webElementGuid>982d4989-266f-47ce-a135-395e800c9933</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
