<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sign in to Katalon</name>
   <tag></tag>
   <elementGuidId>8c13185b-f40d-426e-a2f0-112ab3fe7063</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div[2]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.MuiTypography-root.MuiTypography-h5.MuiCardHeader-title.css-yyb0cb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9a842020-41e1-49fe-80c7-93b91c7cf658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-h5 MuiCardHeader-title css-yyb0cb</value>
      <webElementGuid>a5258f96-5829-42d2-880a-e2f1841ab623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in to Katalon</value>
      <webElementGuid>286f0642-b287-4dc6-8f69-2de00ede7760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;jss13&quot;]/div[@class=&quot;jss25&quot;]/div[@class=&quot;jss27&quot;]/div[@class=&quot;jss28&quot;]/div[@class=&quot;jss29 MuiBox-root css-0&quot;]/div[@class=&quot;MuiCardHeader-root css-faujvq&quot;]/div[@class=&quot;MuiCardHeader-content css-11qjisw&quot;]/span[@class=&quot;MuiTypography-root MuiTypography-h5 MuiCardHeader-title css-yyb0cb&quot;]</value>
      <webElementGuid>0c34f514-92f0-40e8-98c2-435749b7902b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div[2]/div/span</value>
      <webElementGuid>83b91a8b-33ac-464f-8f7b-f98a30a4de48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign in to Katalon']/parent::*</value>
      <webElementGuid>35942e95-3d8c-4b85-a0af-d822cb4b7737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>abb5a7c6-7363-4e74-abb5-19145c0ac714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Sign in to Katalon' or . = 'Sign in to Katalon')]</value>
      <webElementGuid>701eaba4-58a3-441f-939b-3cc29acc9e9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
